apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-gc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-gc
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-gc
  namespace: default
subjects:
  - kind: ServiceAccount
    name: registry-gc
    namespace: default
roleRef:
  kind: Role
  name: registry-gc
  apiGroup: rbac.authorization.k8s.io
