apiVersion: v1
kind: Service
metadata:
  name: vision-analyzer
  namespace: inference
spec:
  type: NodePort
  selector:
    app: vision-analyzer
  ports:
    - port: 8005
      targetPort: 8005
      nodePort: 32005
